server:
  port: 8001

spring:
  application:
    name: cloud-payment-service
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:oracledb
    driver-class-name: oracle.jdbc.driver.OracleDriver
    username: C##SHANE
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.shanezhou.springcloud.entity