spring:
  profiles:
    active: work
  application:
    name: cloud-provider-payment

server:
  port: 8002

eureka:
  instance:
    instance-id: payment8002
    prefer-ip-address: true
  client:
    # 表示是否将自己注册进eureka
    register-with-eureka: true
    # 是否从eurekaServer抓取已有的注册信息，默认为true。
    # 单节点的时候无所谓，集群必须设置为true才能配合ribbon使用负载均衡
    fetch-registry: true
    service-url:
      #      defaultZone: http://localhost:7001/eureka
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka  # 集群版
#mybatis:
#  mapper-locations: classpath:mapper/*.xml
#  type-aliases-package: com.shanezhou.springcloud.entity

---
spring:
  profiles: work
  datasource:
    url: jdbc:p6spy:oracle:thin:@localhost:1521:oracledb
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    username: C##shane
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource


---
spring:
  profiles: mine
  datasource:
    url: jdbc:p6spy:oracle:thin:@localhost:1521:xe
    driver-class-name: oracle.jdbc.driver.OracleDriver
    username: shane
    password: shane
    type: com.alibaba.druid.pool.DruidDataSource
