server:
  port: 7002
eureka:
  instance:
    hostname: eureka7002.com # eureka服务端的实例名称

  server:
#  自我保护机制
    enable-self-preservation: false

  client:
    # false表示不向注册中心注册自己
    register-with-eureka: false
    # false表示自己端就是注册中心，职责是维护服务实例，并不需要去检索服务
    fetch-registry: false
    service-url:
#    单机版 defaultZone 配置
#      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
#    集群版 defaultZone 配置
      defaultZone: http://eureka7001.com:7001/eureka/